sudo: false

# https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
# Travis now defaults to Trusty, which is missing openjdk6.
dist: precise

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

language: scala

# TODO - we'd like to actually test everything, but the process library has a deadlock right now
jdk:
  - openjdk6
#  - oraclejdk7

# WORKAROUND https://github.com/travis-ci/travis-ci/issues/5227
addons:
  hosts: workaround-travis-ci-issue-5227
  hostname: workaround-travis-ci-issue-5227

env:
  matrix:
    - SBT_CMD=";doc;safeUnitTests"
    - SBT_CMD="otherUnitTests"
    - SBT_CMD="scripted actions/*"
    - SBT_CMD="scripted api/*"
    - SBT_CMD="scripted compiler-project/*"
    - SBT_CMD="scripted dependency-management/*1of2"
    - SBT_CMD="scripted dependency-management/*2of2"
    - SBT_CMD="scripted ivy-deps-management/*"
    - SBT_CMD="scripted java/*"
    - SBT_CMD="scripted package/*"
    - SBT_CMD="scripted project/*1of2"
    - SBT_CMD="scripted project/*2of2"
    - SBT_CMD="scripted reporter/*"
    - SBT_CMD="scripted run/*"
    - SBT_CMD="scripted source-dependencies/*1of3"
    - SBT_CMD="scripted source-dependencies/*2of3"
    - SBT_CMD="scripted source-dependencies/*3of3"
    - SBT_CMD="scripted tests/*"
    - SBT_CMD="scripted project-load/*"
    - SBT_CMD="checkBuildScala211"
    - SBT_CMD="repoOverrideTest:scripted dependency-management/*"
    - SBT_CMD="mavenResolverPluginTest:scripted dependency-management/*2of2"
    - SBT_CMD="mavenResolverPluginTest:scripted dependency-management/*1of2 project/transitive-plugins"

notifications:
  email:
    - sbt-dev-bot@googlegroups.com

script:
  - sbt -J-XX:ReservedCodeCacheSize=128m "$SBT_CMD"

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
